export default {
  'APP_FULFILLMENT_VIEW': 'APP_FULFILLMENT_VIEW',
  'APP_LOGIN_VIEW': 'APP_LOGIN_VIEW',
  'APP_PRODUCT_STORE_VIEW': 'APP_PRODUCT_STORE_VIEW',
  'APP_SUPER_USER': 'APP_SUPER_USER',
  'APP_SECURITY_GROUP_CREATE': 'APP_SECURITY_GROUP_CREATE',
  'APP_USER_CREATE': 'APP_USER_CREATE',
  'USERS_APP_VIEW': 'USERS_APP_VIEW'
}