export default {
  'APP_FULFILLMENT_VIEW': 'STOREFULFILLMENT_ADMIN',
  'APP_LOGIN_VIEW': 'SECURITY_CREATE',
  'APP_PRODUCT_STORE_VIEW': 'SECURITY_CREATE',
  'APP_SUPER_USER': 'WEBTOOLS_VIEW',
  'APP_SECURITY_GROUP_CREATE': 'SECURITY_CREATE',
  'APP_USER_CREATE': 'SECURITY_CREATE OR SECURITY_ADMIN',
  'USERS_APP_VIEW': 'USERS_APP_VIEW'
} as any