export default {
  'APP_UPDT_FULFILLMENT_FACILITY': 'STOREFULFILLMENT_ADMIN',
  'APP_UPDT_PICKER_CONFG': 'STOREFULFILLMENT_ADMIN',
  'APP_USER_CREATE': 'SECURITY_CREATE OR SECURITY_ADMIN',
  'APP_UPDT_BLOCK_LOGIN': 'SECURITY_CREATE',
  'APP_UPDT_PASSWORD': 'SECURITY_CREATE',
  'APP_UPDT_PRODUCT_STORE_CONFG': 'SECURITY_CREATE',
  'APP_SECURITY_GROUP_CREATE': 'SECURITY_CREATE',
  'APP_SUPER_USER': 'WEBTOOLS_VIEW',
  'USERS_APP_VIEW': 'USERS_APP_VIEW'
} as any